In [2]:
import torch
import numpy as np
import pandas as pd
from pathlib import Path 
from tqdm import tqdm

%load_ext autoreload
%autoreload 2

/storage/brno2/home/ahajek/miniconda3/envs/BARTtrain/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning:

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html



In [1]:


home = Path("/storage/brno2/home/ahajek/Spektro/MassGenie/")
with open(home / "smaz_to.txt", "r") as f:
    smaz_to = f.read().splitlines()
    nums = [int(x.split("len after PHASE6: ")[1].split(" ")[0]) for x in smaz_to]
    print(sum(nums))

24922354


In [2]:
!ls

10semestr_linz			   Jupyter_runner_bigdata.sh
8semestr			   Jupyter_runner_spektro.sh
9semestr_linz			   MNIST
CloudFlight			   Megatron-LM
DeepSpeed			   Megatron-LM2
JupyterLabPyTorch_GPU.e5121035	   Miniconda3-py310_23.1.0-1-Linux-x86_64.sh
JupyterLabPyTorch_GPU.e5122993	   Multikulti
JupyterLabPyTorch_GPU.e5231393	   Portugese-likeGPT2
JupyterLabPyTorch_GPU.e5231886	   Spektro
JupyterLabPyTorch_GPU.o5121035	   Summarization
JupyterLabPyTorch_GPU.o5122993	   __pycache__
JupyterLabPyTorch_GPU.o5231393	   conda_envs_backup
JupyterLabPyTorch_GPU.o5231886	   core
JupyterLabPyTorch_T4GPU.e5230195   data
JupyterLabPyTorch_T4GPU.e5231378   gpt2czech
JupyterLabPyTorch_T4GPU.e5231613   miniconda3
JupyterLabPyTorch_T4GPU.e5277046   mnist_net.pt
JupyterLabPyTorch_T4GPU.e5307233   modulyApipy
JupyterLabPyTorch_T4GPU.e5307243   ngc
JupyterLabPyTorch_T4GPU.o5230195   nltk_data
JupyterLabPyTorch_T4GPU.o5231378   packages
JupyterLabPyTorch_T4GPU.o5231613   singularity
JupyterLabPyTorch_T4GPU.o52770

In [2]:
preds = [[7, 1, 8, 4, 2, 3, 6, 9, 0], [2, 1, 4, 3, 0]]
idxs = [[7, 1, 8, 4, 2, 3, 6, 9, 0], [2, 1, 4, 3, 0]]
canon_preds = [[] for _ in range(len(preds))]
canon_idxs = [[] for _ in range(len(preds))]

for i, group in enumerate(preds):
    for j, smi in enumerate(group):
        try:
            # canon_preds[i].append(Chem.MolToSmiles(Chem.MolFromSmiles(smi), isomericSmiles=False))
            canon_idxs[i].append(idxs[i][j])
            print(f"index {idxs[i][j]} to group {i}, type type(idxs[i][j]: {type(idxs[i][j])}")
            print(canon_idxs)
            # print(canon_idxs)
        except Exception:
            pass

print(canon_idxs)

index 7 to group 0, type type(idxs[i][j]: <class 'int'>
[[7], []]
index 1 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1], []]
index 8 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8], []]
index 4 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4], []]
index 2 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2], []]
index 3 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3], []]
index 6 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6], []]
index 9 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6, 9], []]
index 0 to group 0, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6, 9, 0], []]
index 2 to group 1, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6, 9, 0], [2]]
index 1 to group 1, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6, 9, 0], [2, 1]]
index 4 to group 1, type type(idxs[i][j]: <class 'int'>
[[7, 1, 8, 4, 2, 3, 6, 9, 0], [2, 1, 4]]
index 3 to group

In [11]:
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_file("Spektro/MassGenie/tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model")

In [2]:
from Spektro.MassGenie.dataset import SpectroDataset, SpectroDataCollator

data_range = range(0, 10) ####!!!!!########
data_path = "Spektro/MassGenie/data/datasets/DEBUG/DEBUG_valid.pkl"
dataset = SpectroDataset(data_path, eval_mode=True)#[0:20] ####!!!!!########
subset = torch.utils.data.Subset(dataset, data_range) ####!!!!!########
loader = torch.utils.data.DataLoader(subset,
                                     batch_size=5,
                                     collate_fn=SpectroDataCollator(eval_mode=True),
                                     drop_last=False,
                                     shuffle=False)


In [6]:
for x in iter(int, 1):
    break
df = dataset.data
df.iloc[]

In [47]:
for batch in loader:
    print(batch)
    break

{'input_ids': tensor([[ 26,  27,  28,  30,  38,  39,  40,  41,  42,  43,  44,  45,  46,  50,
          51,  52,  53,  54,  55,  56,  58,  59,  60,  63,  64,  65,  66,  67,
          68,  69,  70,  72,  75,  77,  78,  79,  80,  81,  82,  83,  87,  89,
          90,  91,  92,  93,  94,  95, 104, 105, 106, 107, 108, 109, 110, 116,
         117, 118, 119, 120, 121, 122, 129, 131, 132, 133, 136, 145, 146, 147,
         148, 149, 150, 159, 160, 161, 162, 163, 164, 165, 166, 173, 174, 175,
         176, 177, 188, 189, 190, 200, 204, 205, 206, 218, 219, 232, 233, 234,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,

In [ ]:
import pandas as pd

s = slice(2, 4)
a = pd.Series([9,8,7,6])
torch.tensor(a[s])
# torch.tensor(a).shape

ValueError: could not determine the shape of object type 'Series'

In [4]:
data = pd.read_pickle("Spektro/MassGenie/data/datasets/DEBUG/DEBUG_valid.pkl")

In [21]:
%%time
r = range(0,50)
for i, x in enumerate(data.iloc[r].smiles.()):
    print(i, x[0], x[1])


AttributeError: 'Series' object has no attribute 'iter'

In [9]:
range(20, 200)

AttributeError: 'range' object has no attribute 'end'

In [60]:
f = open("Spektro/MassGenie/test_smaz", "r")

In [57]:
next(f, None)

In [59]:
import json
json.loads(None)

TypeError: the JSON object must be str, bytes or bytearray, not NoneType

In [62]:
list(zip([1,2,3], [4,5,6], [7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [63]:
d = {"a": 1, "b": 2, "c": 3}
d.keys()

dict_keys(['a', 'b', 'c'])

In [65]:
list(zip(d.keys(), d.values(), [4,3,2]))

[('a', 1, 4), ('b', 2, 3), ('c', 3, 2)]

In [66]:
d.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [72]:
np.stack(np.array(zip([1,2,3], [4,5,6], [7,8,9])))


TypeError: dispatcher for __array_function__ did not return an iterable

In [93]:
a = np.array([0])

def foo(a):
    a[0] += 1

foo(a) 
a

array([1])

In [78]:
a = np.array([[1,6], [2,-2], [3,-3]])
index = np.argsort(a[:, 1])
a[index], index

(array([[ 3, -3],
        [ 2, -2],
        [ 1,  6]]),
 array([2, 1, 0]))

In [92]:
a = np.array([1,2])
b = np.array([[5,6,7], [2,3,4]])

a[:2] += b[:, 2]
a

array([8, 6])

In [91]:
b[:, :2]

array([[5, 6],
       [2, 3]])

In [95]:
json.loads("")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [97]:
data = pd.read_pickle('Spektro/MassGenie/data/datasets/30M/30M_valid.pkl')

In [113]:
import time
time.strftime("%H:%M:%S", time.gmtime(21722.93333))

'06:02:02'

In [114]:
data

smiles  \
16                              CCNC(c1cnn2c1OCCC2)CC=C=C   
19            CCC1CN(C(=O)C)C(CN1C(=O)c1nc2ccccc2cc1Cl)CC   
50            OC1CNCC1N=c1[nH]c(ncc1[N+](=O)[O-])C(C)(C)C   
59      COC(=O)Cc1ccc(c(c1)[N+](=O)[O-])NCCc1cnc2n(c1)...   
64      O=C(c1ccc2c(c1)n[nH]n2)Nc1ccc(cc1)NS(=O)(=O)c1...   
...                                                   ...   
374955   O=C(C1CC(=O)N(C1)C1CCS(=O)(=O)C1)OCC1OCC(C1)(C)C   
374968          OCCN(C1CCN(CC1)C(=O)C1CC1)CC1CCC(CC1)(C)C   
374972        CC=C(C(=O)N1CC(C(C1)CNC(=O)CC1CCCC1(F)F)C)C   
374986                   NC1CC2COCC(C1)C2NCC(c1ccn(n1)C)C   
374988                     FC(CNCCN1CCOC(C1)C(C)(C)C)(F)F   

                                                input_ids  \
16      [26, 27, 28, 30, 38, 39, 40, 41, 42, 43, 44, 4...   
19      [36, 38, 39, 40, 41, 42, 43, 44, 49, 50, 51, 5...   
50      [30, 33, 34, 36, 38, 39, 40, 41, 42, 43, 44, 4...   
59      [33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 4...   
64      [33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 4...   
...                                                   ...   
374955  [30, 33, 39, 40, 41, 42, 43, 44, 45, 47, 48, 4...   
374968  [33, 39, 41, 42, 43, 44, 45, 53, 54, 55, 56, 5...   
374972  [29, 30, 33, 36, 38, 39, 40, 41, 42, 43, 44, 4...   
374986  [30, 33, 36, 38, 39, 40, 41, 42, 43, 44, 45, 4...   
374988  [15, 27, 28, 29, 30, 33, 37, 38, 39, 40, 41, 4...   

                                                   labels  \
16      [1233, 224, 283, 11, 70, 20, 284, 21, 70, 20, ...   
19      [1233, 224, 276, 20, 263, 11, 38, 260, 50, 12,...   
50      [1233, 224, 286, 20, 400, 20, 49, 32, 70, 20, ...   
59      [1233, 224, 285, 260, 50, 12, 279, 20, 280, 11...   
64      [1233, 224, 50, 32, 38, 11, 70, 20, 280, 21, 7...   
...                                                   ...   
374955  [1233, 224, 50, 32, 38, 11, 38, 20, 261, 260, ...   
374968  [1233, 224, 321, 11, 38, 20, 269, 11, 261, 20,...   
374972  [1233, 224, 261, 32, 38, 11, 38, 260, 50, 12, ...   
374986  [1233, 224, 265, 20, 261, 21, 306, 11, 38, 20,...   
374988  [1233, 224, 495, 11, 447, 20, 292, 11, 38, 20,...   

                                   decoder_attention_mask  \
16      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
19      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
50      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
59      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
64      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
...                                                   ...   
374955  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374968  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374972  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374986  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374988  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   

                                   encoder_attention_mask  \
16      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
19      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
50      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
59      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
64      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
...                                                   ...   
374955  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374968  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374972  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374986  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
374988  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   

                                             position_ids  
16      [3, 6, 5, 5, 5, 9, 8, 9, 9, 7, 9, 8, 6, 3, 7, ...  
19      [3, 0, 6, 5, 7, 8, 8, 6, 3, 1, 5, 4, 6, 6, 5, ...  
50      [5, 1, 1, 3, 3, 7, 6, 9, 9, 8, 9, 6, 5, 4, 7, ...  
59      [3, 7, 0, 6, 8, 6, 6, 6, 8, 7, 5, 4, 8, 9, 9, ...  
64      [3, 2, 2, 1, 3, 7, 5, 6, 4, 6, 6, 6, 0, 2, 4, ...  
...                       

In [121]:
with open('Spektro/MassGenie/data/datasets/30M/30M_valid.smi', 'w') as f:
    for s in tqdm(data.smiles):
        f.write(s + '\n')

100%|██████████| 1246114/1246114 [00:00<00:00, 3204466.46it/s]


In [10]:
import plotly.express as px
df = px.data.tips()
fig = px.box(df, x="time", y="total_bill", points="all")
type(fig)

plotly.graph_objs._figure.Figure

In [4]:
fig = px.box(x=["a", "b"], y="total_bill", points="all")


ValueError: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'y' is of type str or int.

In [2]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
from collections import defaultdict

a = defaultdict(list)
a["a"].append(1)

In [8]:
a

defaultdict(list, {'a': [1]})